### PR TITLE
Fixed worker schema filename in worker_create.sh.

### PR DESCRIPTION
**Pull request by jimmysoda**
Fixes issue #1.

### CODE REVIEW

**Comment by jimmysoda** [comment]
[Line 41](https://github.com/spatialos/CppBlankProject/blob/master/worker_create.sh#L41) makes the string replacement in the file contents, not the filename itself:
```
sed -i "s/$OLD_NAME/$NEW_NAME/g" spatialos.$NEW_NAME.worker.json
```

Without my change this line does nothing on a clean destination directory. `spatialos.$OLD_NAME.worker.json` is copied to `$DEST_PROJECT_PATH/workers/$NEW_NAME` in [Line 12](https://github.com/spatialos/CppBlankProject/blob/master/worker_create.sh#L12) but it is not renamed to `spatialos.$NEW_NAME.worker.json`.

**Comment by tenevdev** [comment]
Sorry, I meant [line 41 after your changes, with the `mv` command](https://github.com/jimmysoda/SpatialOS-CppBlankProject/blob/3797e87f0d23529d58c301a2b26ee7c3216d1a6e/worker_create.sh#L41)

```
# Rename worker configuration file
mv spatialos.$OLD_NAME.worker.json spatialos.$NEW_NAME.worker.json
```

At this point I'm very curious to find out what weird shell behaviour actually caused the issue for you 😃 (and also a bit disappointed I didn't create this as a static binary instead in the first place).

**Comment by jimmysoda** [comment]
I used the MINGW64 shell installed with the Git command-line tools in Windows.

When I opened the PR I had finished the Unity Pirates tutorial and decided to use the same project for the C++ tutorial instead of using the C++ Pirates tutorial project. I wasn't able to reproduce the issue with a clean clone of this repository when copying the _External_ worker to a clean clone of another one of the example/starter SpatialOS projects. 

The only way I was able to reproduce the issue was by attempting to copy to an empty directory, e.g.,
```
$ ./worker_create.sh External External0 ../empty-dir
+ OLD_NAME=External
+ NEW_NAME=External0
+ DEST_PROJECT_PATH=../empty-dir
+ mkdir -p ../empty-dir/workers/External0
+ cp -rT workers/External ../empty-dir/workers/External0
+ mkdir -p ../empty-dir/dependencies/
+ cp dependencies/CMakeLists.txt ../empty-dir/dependencies/
+ cp schema/CMakeLists.txt ../empty-dir/schema
+ sed -i /blank/d ../empty-dir/schema/CMakeLists.txt
sed: can't read ../empty-dir/schema/CMakeLists.txt: Not a directory
```

I'm in favor of closing this issue since the usage comment in [line 4](https://github.com/spatialos/CppBlankProject/blob/master/worker_create.sh#L4) implies that the destination directory is a SpatialOS project.

**Comment by tenevdev** [comment]
Yes, you're right I assumed the worker is being added to an existing project. This implies [several things](https://docs.improbable.io/reference/12.0/developing/project-structure) - one being that there is a `schema` directory in the project root. This assumption is of course violated when copying to an empty directory causing the issue you demonstrated. Having said that, adding some more sensible error-reporting to this script definitely won't hurt.

**Pull request closed without merging**
